name: Deploy to S3 via OIDC

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
      version:
        description: 'Version to deploy'
        required: false
        type: string

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
  S3_BUCKET: ${{ vars.BUCKET_NAME }}  # ⬅️ CORREGIDO

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment || 'production' }}
      url: https://${{ vars.BUCKET_NAME }}.s3.${{ env.AWS_REGION }}.amazonaws.com  # ⬅️ CORREGIDO

    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GitHubActions-Deploy

    - name: Debug Environment variables
      run: |
        echo "Environment: ${{ github.event.inputs.environment || 'production' }}"
        echo "AWS Region: ${{ env.AWS_REGION }}"
        echo "S3 Bucket: ${{ env.S3_BUCKET }}"
        echo "AWS Role ARN: ${{ vars.AWS_ROLE_ARN }}"
        echo "Git SHA: ${{ github.sha }}"
        echo "Git Ref: ${{ github.ref }}"

    - name: Create deployment file
      run: |
        TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        cat > deployment-info.json << EOF
        {
          "deployment": {
            "timestamp": "$TIMESTAMP",
            "commit_sha": "${{ github.sha }}",
            "commit_message": "${{ github.event.head_commit.message }}",
            "branch": "${{ github.ref }}",
            "repository": "${{ github.repository }}",
            "run_id": "${{ github.run_id }}",
            "environment": "${{ github.event.inputs.environment || 'production' }}",
            "version": "${{ github.event.inputs.version || '1.0.0' }}"
          },
          "application": {
            "bucket": "${{ env.S3_BUCKET }}",
            "region": "${{ env.AWS_REGION }}",
            "role_arn": "${{ vars.AWS_ROLE_ARN }}"
          }
        }
        EOF
        
        echo "=== Deployment File Content ==="
        cat deployment-info.json

    - name: Upload to S3
      run: |
        # Crear nombre de archivo único
        FILENAME="deployments/deploy-${{ github.sha }}-${{ github.run_id }}.json"
        
        # Subir a S3
        aws s3 cp deployment-info.json s3://${{ env.S3_BUCKET }}/$FILENAME
        
        # También subir como latest.json
        aws s3 cp deployment-info.json s3://${{ env.S3_BUCKET }}/deployments/latest.json
        
        echo "File uploaded to: s3://${{ env.S3_BUCKET }}/$FILENAME"
        echo "Latest file: s3://${{ env.S3_BUCKET }}/deployments/latest.json"

    - name: Verify S3 upload
      run: |
        # Verificar que el archivo existe en S3
        aws s3 ls s3://${{ env.S3_BUCKET }}/deployments/ --recursive --human-readable
        
        # Obtener información del archivo latest
        echo "=== Latest Deployment Info ==="
        aws s3 cp s3://${{ env.S3_BUCKET }}/deployments/latest.json - || echo "Latest file not found"